"""HTML formatter utility for formatting email content."""

from datetime import datetime

class HTMLFormatter:
    """Responsible for formatting content into HTML."""
    
    @staticmethod
    def format_summary_to_html(summary: str, include_timestamp: bool = True) -> str:
        """Formats a text summary into HTML format."""
        timestamp = f"<p><em>Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>" if include_timestamp else ""
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
                h1 {{ color: #2c3e50; }}
                .summary {{ background-color: #f9f9f9; padding: 15px; border-left: 4px solid #3498db; margin-bottom: 20px; }}
                .disclaimer {{ font-size: 0.8em; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 10px; margin-top: 30px; }}
            </style>
        </head>
        <body>
            <h1>IT Circulars Summary</h1>
            <div class="summary">
                {summary.replace('\\n', '<br>')}
            </div>
            {timestamp}
            <div class="disclaimer">
                <p>Disclaimer: This is an automated summary generated by an AI. Please verify information from original sources.</p>
            </div>
        </body>
        </html>
        """
        return html_content
